
lightbox: true
title-block-categories: true
number-sections: false
image-lazy-loading: true
bibliography: references.bib
favicon: "assets/favicon.svg"
site-url: "https://ishankr.com"
citeproc: true
project:
  type: website
  output-dir: "docs"
  preview:
    port: 4209
  render:
    - "index.qmd"
    - "./posts/**/*.qmd"
    - "./slides/**/*.qmd"
    - "./talks/**/*.qmd"
    - "./qmd/**/*.qmd"
    - "!*old*"
    - "!/drafts/"
  resources:
    - ./static/files/resume.pdf
    - ./static/files/superconductivity.pdf
    - ./static/files/oneapi-talk/
    - ./static/fonts/**/**/*.woff2
affiliation: "[UIUC](https://illinois.edu)"
author:
  name: "Ishan Buyyanapragada"
  url: "https://ishankr.com"
  email: "ibuyy@illinois.edu"
  affiliation: "[UIUC](https://illinois.edu)"
  affiliation-url: "https://illinois.edu"
citation: true
# citation:
#   author: Sam Foreman
#   type: webpage
#   url: https://samforeman.me
execute:
  # keep-ipynb: true
  # keep-md: true
  freeze: auto
google-scholar: true
metadata-files:
  - quarto/_website.yml
  - quarto/_format.yml
  # - posts/_metadata.yml
  # - posts/_metadata.yml
  # - talks/_metadata.yml
  # - _reveal.yml
